version: "3.8"
services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    image: estat-sac:py39
    container_name: estat-sac-dev

    stdin_open: true
    tty: true

    ports:
      - "1236:80"
      
    volumes:
      - ./app:/code/app


      
