name: Daily Job

on:
  schedule:
    - cron: "0 0 * * *" # 毎日0時に実行

jobs:
  run-job:
    name: Run Daily Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9' 
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt
      - run: python app/create_estat_data.py "00200561" "${{ secrets.APPID }}" "app/resource"
      - name: 差分を push
        run: |
          git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          if (git diff --shortstat | grep '[0-9]'); then \
            git add .; \
            git commit -m "Daily Job Get Data Commit !!"; \
            git push origin HEAD:${GITHUB_REF}; \
          fi
