name: Daily Job

on:
  schedule:
    - cron: "0 0 * * *" # 毎日0時に実行

jobs:
  run-job:
    name: Run Daily Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9' 
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt
      - run: python app/create_estat_data.py "00200561" "${{ secrets.APPID }}" "app/resource"
  
      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add app/resource
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m "resource update [bot] "
          fi
  
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main      
      
